name = "JPetalo"
authors = ["jjgomezcadenas"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pandas = "eadc2687-ae89-51f9-a5d9-86b5a6373a9c"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StrFormat = "b5087856-efa9-5a6d-8e6f-97303a7af894"
StrLiterals = "68059f60-971f-57ff-a2d0-18e7de9ccc84"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1.6.0"
